### ISSUE TITLE
Cannot cache an empty array

### ISSUE THREAD

**Issue by Andrewsville** [Kdyby/DoctrineCache#12]
We have encountered this issue when using Doctrine annotation reader. When its result is an empty array, it tries to re-read annotations for the particular file on every request because of [this ternary](https://github.com/Kdyby/DoctrineCache/blob/master/src/Kdyby/DoctrineCache/Cache.php#L64) that makes DoctrineCache behave like there was no value cached.

**Comment by enumag** [comment]
Yeah, the code should look like this instead.

```
$data = $this->cache->load($id);
return $data !== NULL ? $data : FALSE;
```

Can you send a pull request?

**Comment by enumag** [comment]
By the way I believe this is what was causing some of my performance problems before I stopped using this class. Thanks for finding the problem!

**Comment by enumag** [comment]
Closed by https://github.com/Kdyby/DoctrineCache/commit/93fd43c9d972bd59b42f4499ae9bc94cdb554e99
