### ISSUE TITLE
Redis

### ISSUE THREAD

**Issue by solcik** [Kdyby/DoctrineCache#5]
Is it possible to do "Kdyby\DoctrineCache\RedisCache " in same manner as the [MemcacheCache](https://github.com/Kdyby/DoctrineCache/blob/master/src/Kdyby/DoctrineCache/MemcacheCache.php)?

When I tried to use redis option for cache in some of your packages (doctrine, annotations), it fails, because setter for Redis client on Doctrine RedisCache class is not called.

Now I am using apc, so it is no longer a problem, but still .)

**Comment by fprochazka** [comment]
Hi, for metadata and query cache (not result cache), you should definitely use APCu - it's by far the fastest.

But yes, you have a good point and the `RedisCache` should be fixed :) I'd welcome a pullrequest.

**Comment by solcik** [comment]
Ok, not now, but I will try.

**Comment by enumag** [comment]
This was fixed by https://github.com/Kdyby/DoctrineCache/commit/3d44162f7946749cc08d264aea2c2bc7224eadc7, right?

**Comment by fprochazka** [comment]
Yes :)
